server:
  port: 8083

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 192510
    url: jdbc:mysql://111.229.16.229:3306/ms_class
    username: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  application:
    name: ms-class
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
#        health-check-path: /actautor/health
        #        健康检查时间间隔 10S
        health-check-interval: 10s
        #       consul 请求健康检查超时时间
        health-check-timeout: 10s
        #        健康检查持续不OK达到该时间consul将会删除该实例
        health-check-critical-timeout: 100s
#        表示注册使用ip而不是hostname
        prefer-ip-address: true
        instance-id: ${spring.application.name}-${server.port}-${spring.cloud.client.hostname}
management:
  endpoints:
    web:
      exposure:
        include: '*'

#设置调用 ms-user 的ribbon的轮询策略
#ms-user:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule


#feign类的日志级别
logging:
  level:
    com.springcloud.feign.MsUserFeignClient: debug

#  用配置的方式设置日志级别，上面那一段不能少 ，细粒度配置
#feign:
#  client:
#    config:
#      ms-user:
#        loggerLevel: full

#feign的全局配置
feign:
  client:
    config:
      default:
        loggerrLevel: full
